name: chemcards
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pydantic
  - rdkit
  - pillow
  - tqdm
  - requests
  - numpy
  - idna
  - easydict
  - yaml
  - pyyaml
prefix: /Users/alexpayne/miniconda3/envs/chemcards
