name: chemcards
channels:
  - conda-forge
dependencies:
  - numpy
  - pillow
  - yaml
  - easydict
  - pip
  - idna
  - pydantic
  - rdkit
  - requests
  - tqdm
  - pyyaml
  - click
  - pyttk
prefix: /Users/apayne/miniforge3/envs/chemcards
